spring:
    datasource:
        url: jdbc:mysql://localhost::3306/blog_db?useSSL=false&serverTimezone=UTC
        username: root
        password: root

        jpa:
          hibernate :
            ddl-auto: update
            show-sql: true

            properties:
              hibernates:
                format_sql: true
    server:
      port: 8080

     app:
       jwt:
         secret:
           expiration-ms: 86400000